// Minimal constants for components that haven't been fully converted yet
export const COLORS = {
  lemonIcing: '#F9F1D2',
  nimbusCloud: '#D5D5D7',
  raindropsOnRoses: '#EAD8DE',
  cloudDancer: '#F0F0F0',
  iceMelt: '#D6E4F0',
  peachDust: '#F3DFD1',
  almostAqua: '#D1DBCB',
  orchidTint: '#E1D5E3',
  textPrimary: '#2D3436',
  textSecondary: '#636E72',
  accent: '#DDEBF4',
  fukuBrand: '#c0b7c9'
} as const;

export const THEME = {
  assistantBubble: COLORS.fukuBrand,
  userBubble: COLORS.iceMelt,
  sidebar: COLORS.cloudDancer,
  header: COLORS.nimbusCloud,
  background: COLORS.cloudDancer,
  input: COLORS.lemonIcing,
} as const;

export const GLASS_STYLES = {
  base: {
    backdropFilter: 'blur(10px)',
    border: '1px solid rgba(0, 0, 0, 0.05)',
  },
  elevated: {
    backdropFilter: 'blur(20px)',
    boxShadow: '0 2px 4px -1px rgba(0,0,0,0.1), 0 1px 2px rgba(255,255,255,0.5), inset 0 1px 2px rgba(255,255,255,0.3), inset 0 -1px 2px rgba(0,0,0,0.05)',
  },
  subtle: {
    boxShadow: '0 2px 4px -1px rgba(0,0,0,0.05), inset 0 1px 2px rgba(255,255,255,0.3)',
  },
} as const;

// Homescreen welcome messages (shown when no action is active)
export const WELCOME_MESSAGES = [
"Ready for your next command.",
"How can I assist you today?",
"Ready to handle any task.",
"Your digital handyman is online.",
"What can I do for you today?",
"Let's get things done together.",
"What's our mission for today?",
"At your service for any task.",
"How can I make your work easier?",
"Tell me what to execute next."
] as const;

// Action-specific prompts for each QuickAction mode
export const ACTION_PROMPTS = {
  Files: [
    "Describe the file you're looking for...",
    "What file do you need?",
    "Tell me about the file...",
    "What are you looking for?",
    "Which file can I help you find?",
    "Describe what you're searching for...",
    "What file are we hunting?",
    "Lost something? Describe it...",
    "Paint me a picture of that file...",
    "What does the file look like?",
    "Give me a hint about the file...",
    "What's in the file you need?",
    "Describe the document...",
    "What kind of file is it?",
    "Tell me more about it...",
    "What should I search for?",
    "Name, content, or type?",
    "What do you remember about it?",
    "Any details about the file?",
    "What's the file about?",
    "Describe it in your words...",
    "What were you working on?",
    "When did you last see it?",
    "What project was it for?",
    "Any keywords come to mind?",
    "What's inside the file?",
    "Give me something to go on...",
    "What topic is it about?",
    "Describe the contents...",
    "What format is it?",
    "Where might it be hiding?",
    "What's the file called?",
    "Any part of the name?",
    "What type of document?",
    "Describe it naturally...",
    "Just tell me what you need...",
    "What are we finding today?",
    "Describe your lost file...",
    "What should I look for?",
    "Give me the details...",
    "What's the gist of it?",
    "Anything you remember?",
    "What was it related to?",
    "Describe it however you like...",
    "What's the file contain?",
    "Any clues for me?",
    "What do you recall?",
    "Tell me what you know...",
    "What's the subject?",
    "Describe away...",
  ],
  Agents: [
    "What can an agent help you with?",
    "Which task needs automation?",
    "What should the agent do?",
    "Describe the task...",
    "What workflow do you need?",
    "How can I assist you?",
    "What's the mission?",
    "Tell me what to automate...",
    "What process needs help?",
    "Describe your request...",
    "What job should I tackle?",
    "How can agents help today?",
    "What's on your to-do list?",
    "Which task is it?",
    "What needs doing?",
    "Describe the workflow...",
    "What should I handle?",
    "Tell me the task...",
    "What can I automate?",
    "What's the goal?",
    "Which process needs help?",
    "What should I work on?",
    "Describe what you need...",
    "What's the assignment?",
    "How can I help today?",
    "What task is it?",
    "Tell me what to do...",
    "What needs automation?",
    "Describe the job...",
    "What should I tackle?",
    "Which workflow is it?",
    "What can I do for you?",
    "What's the request?",
    "Tell me the goal...",
    "What process is it?",
    "Describe your task...",
    "What needs handling?",
    "Which job is it?",
    "What should I automate?",
    "Tell me what's needed...",
    "What's the workflow?",
    "Describe the process...",
    "What task needs help?",
    "How can I assist?",
    "What's on the agenda?",
    "Which task today?",
    "What do you need done?",
    "Tell me the assignment...",
    "What should I do?",
    "Describe it...",
  ],
  Workflows: [
    "What workflow do you want to run?",
    "Select a saved workflow...",
    "Create a new automation...",
    "Which task sequence?",
    "Run which workflow?",
    "Automate what process?",
    "Which prompt chain?",
    "Select automation...",
    "What to automate?",
    "Which sequence to run?",
  ],
  Terminal: [
    "What command to run?",
    "Execute which command?",
    "Run what in terminal?",
    "Which shell command?",
    "What to execute?",
    "Run which script?",
    "Execute what?",
    "Which command?",
    "What to run?",
    "Shell command?",
  ],
} as const;

// Active colors for QuickAction buttons (darker/more saturated versions)
export const ACTION_ACTIVE_COLORS = {
  Files: '#5a7a4a',
  Agents: '#9a5a6a',
  Space: '#8a7a3a',
  Cleanup: '#7a5a8a',
} as const;

export const QUICK_ACTIONS = [
  { id: 'Files', color: '#D1DBCB', activeColor: '#5a7a4a', placeholder: 'Which file are you looking for?', opensPanel: true },
  { id: 'Agents', color: '#EAD8DE', activeColor: '#9a5a6a', placeholder: 'Ask an agent for help...', opensPanel: false },
  { id: 'Workflows', color: '#F9F1D2', activeColor: '#8a7a3a', placeholder: 'Select or create a workflow...', opensPanel: true },
  { id: 'Terminal', color: '#E1D5E3', activeColor: '#7a5a8a', placeholder: 'Run commands...', opensPanel: true },
] as const;

export const MOCK_FILES = [
  { id: '1', name: 'invoice_2023_oct.pdf', path: '/Documents/Work/Invoices', size: '1.2 MB', category: 'Work', safeToRemove: true, lastUsed: '2023-10-15' },
  { id: '2', name: 'draft_presentation_v2.pptx', path: '/Desktop/Drafts', size: '45 MB', category: 'Project', safeToRemove: true, lastUsed: '2023-11-20' },
  { id: '3', name: 'kernel_panic_log_2024.txt', path: '/System/Logs', size: '2 KB', category: 'System', safeToRemove: false, lastUsed: '2024-01-05' },
  { id: '4', name: 'large_cache_file.tmp', path: '/AppData/Local/Temp', size: '2.4 GB', category: 'Temp', safeToRemove: true, lastUsed: '2023-05-10' },
  { id: '5', name: 'family_photo_vacation.jpg', path: '/Pictures/2023', size: '5.6 MB', category: 'Personal', safeToRemove: false, lastUsed: '2023-12-25' },
  { id: '6', name: 'node_modules_old_project', path: '/Dev/archive/project-x', size: '850 MB', category: 'Dev', safeToRemove: true, lastUsed: '2022-8-12' }
] as const;

export const MOCK_MESSAGES = [
  { id: 'm1', app: 'Slack', user: 'Sarah', text: 'Hey, did you finish the Fuku UI design?', timestamp: '2 hours ago' },
  { id: 'm2', app: 'Discord', user: 'DevTeam', text: 'The build is failing on the log analyzer module.', timestamp: '1 day ago' },
  { id: 'm3', app: 'iMessage', user: 'Mom', text: 'Call me when you are free!', timestamp: '5 mins ago' }
] as const;
